export const PROFILE_DATA = {
  user: "John Doe",
  userImage: "./assets/profile.jpg",
  image: `https://sig1.co/logo-1`,
  name: "joinsigma",
  posts_no: 465,
  followers: 1723,
  following: 9,
  subheader: "Sigma School | Tech Education & Services",
  account_type: "Education",
  description: `
    🚨 Upskill yourself, learn to code
    👨‍💻 Develop full stack web & mobile apps
    🤝🏻 Build real world projects
    💯 Free if you don’t land a tech job
    `,
  link: "linktr.ee/joinsigma",
  lists: [
    { image: "./assets/sigma-list-meetups.jpg", description: "Meet-ups" },
    { image: "./assets/sigma-list-reviews.jpg", description: "Reviews" },
    { image: "./assets/sigma-list-shoutouts.jpg", description: "Shoutouts" },
    { image: "./assets/sigma-list-hiring.jpg", description: "Hiring" },
    { image: "./assets/sigma-list-events.jpg", description: "Events" },
    { image: "./assets/sigma-list-faqs.jpg", description: "FAQs" },
    { image: "./assets/sigma-list-mentors.jpg", description: "Mentors" },
  ],
  posts: [
    {
      image: "https://picsum.photos/id/123/500/500",
      description: "Post 1 description",
      date: new Date().toISOString(),
      likes: 15,
      comments: 5,
    },
    {
      image: "https://picsum.photos/id/124/500/500",
      description: "Post 2 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/125/500/500",
      description: "Post 3 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/126/500/500",
      description: "Post 4 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/127/500/500",
      description: "Post 5 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/128/500/500",
      description: "Post 6 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
  ],
  reels: [
    {
      image: "https://picsum.photos/id/129/500/500",
      description: "Post 1 description",
      date: new Date().toISOString(),
      likes: 15,
      comments: 5,
    },
    {
      image: "https://picsum.photos/id/130/500/500",
      description: "Post 2 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/131/500/500",
      description: "Post 3 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/132/500/500",
      description: "Post 4 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/133/500/500",
      description: "Post 5 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/134/500/500",
      description: "Post 6 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
  ],
  taggeds: [
    {
      image: "https://picsum.photos/id/135/500/500",
      description: "Post 1 description",
      date: new Date().toISOString(),
      likes: 15,
      comments: 5,
    },
    {
      image: "https://picsum.photos/id/136/500/500",
      description: "Post 2 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/137/500/500",
      description: "Post 3 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/139/500/500",
      description: "Post 4 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/140/500/500",
      description: "Post 5 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
    {
      image: "https://picsum.photos/id/141/500/500",
      description: "Post 6 description",
      date: new Date().toISOString(),
      likes: 30,
      comments: 10,
    },
  ],
};
